source 'https://rubygems.org'
gem 'rails', '3.2.12'
#gem 'mysql2'
gem 'sqlite3', '~> 1.3.6'
gem 'softwareplanet-cms', :path => '../'
#gem 'activefile', :path => 'activefile'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'



gem 'codemirror-rails' 
gem 'aloha-rails' 
#=   CMS REQUIREMENTS END   =#
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'haml'

gem 'haml' 
